CREATE TABLE `geolminocc` (
  `OID` int NOT NULL,
  `Site_ID` varchar(255) NOT NULL,
  `Ftr_ID` varchar(255) NOT NULL,
  `Ftr_Name` varchar(255) DEFAULT NULL,
  `Last_Updt` date DEFAULT NULL,
  `Ftr_Type` varchar(255) DEFAULT NULL,
  `Commodity` varchar(255) NOT NULL,
  `Value_Mat` text,
  `Assoc_Mat` text,
  `Min_Style` text,
  `Min_Age` varchar(255) DEFAULT NULL,
  `Host_Age` varchar(255) DEFAULT NULL,
  `Host_Name` text,
  `Host_Litho` text,
  `Alteration` text,
  `Ref_ID` varchar(255) DEFAULT NULL,
  `Remarks` text,
  PRIMARY KEY (`OID`,`Site_ID`,`Ftr_ID`,`Commodity`),
  KEY `geolminocc_site` (`Site_ID`),
  KEY `geolminocc_ftr` (`Ftr_ID`),
  CONSTRAINT `geolminocc_ftr` FOREIGN KEY (`Ftr_ID`) REFERENCES `feature` (`Ftr_id`),
  CONSTRAINT `geolminocc_site` FOREIGN KEY (`Site_ID`) REFERENCES `site` (`site_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_