CREATE TABLE `resources` (
  `OBJECTID` int NOT NULL,
  `Site_ID` varchar(255) DEFAULT NULL,
  `Ftr_ID` varchar(255) DEFAULT NULL,
  `Ftr_Name` varchar(255) DEFAULT NULL,
  `Last_Updt` date DEFAULT NULL,
  `Material` varchar(255) DEFAULT NULL,
  `Rsrc_Date` int DEFAULT NULL,
  `Mat_Type` varchar(255) DEFAULT NULL,
  `Mat_Amnt` varchar(255) DEFAULT NULL,
  `Mat_Units` varchar(255) DEFAULT NULL,
  `Grade` varchar(255) DEFAULT NULL,
  `Grade_Unit` varchar(255) DEFAULT NULL,
  `CutOffGrad` varchar(255) DEFAULT NULL,
  `CutOffUnit` varchar(255) DEFAULT NULL,
  `Contained` double DEFAULT NULL,
  `Cont_Units` varchar(255) DEFAULT NULL,
  `MatAmntSI` varchar(255) DEFAULT NULL,
  `MatUnitsSI` varchar(255) DEFAULT NULL,
  `GradeSI` varchar(255) DEFAULT NULL,
  `GradUnitSI` varchar(255) DEFAULT NULL,
  `COG_SI` varchar(255) DEFAULT NULL,
  `COU_SI` varchar(255) DEFAULT NULL,
  `CntSIComAm` float DEFAULT NULL,
  `CntSIComUt` varchar(255) DEFAULT NULL,
  `CntSICom` varchar(255) DEFAULT NULL,
  `Rsrc_Class` varchar(255) DEFAULT NULL,
  `Rsrc_Descr` varchar(255) DEFAULT NULL,
  `Rsrc_Code` varchar(255) DEFAULT NULL,
  `Ref_Detail` text,
  `Ref_ID` varchar(255) DEFAULT NULL,
  `Remarks` text,
  PRIMARY KEY (`OBJECTID`),
  KEY `Site_ID` (`Site_ID`),
  KEY `Ftr_ID` (`Ftr_ID`),
  CONSTRAINT `resources_ibfk_1` FOREIGN KEY (`Site_ID`) REFERENCES `site` (`site_id`),
  CONSTRAINT `resources_ibfk_2` FOREIGN KEY (`Ftr_ID`) REFERENCES `feature` (`Ftr_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
